### ISSUE TITLE
Port over "Introducing . . ." pages from the wiki

### ISSUE THREAD

**Issue by jeffgeorge** [sabnzbd/sabnzbd.github.io#1]
Found two pages we missed during the import:
- [Introducing 1.0.0](http://sabnzbd.wikidot.com/introducing-1-0-0)
- [Introducing 0.7.0](http://sabnzbd.wikidot.com/introducing-0-7-0)

(Found them because they were referenced in the /topic of #sabnzbd)

**Comment by jeffgeorge** [comment]
Ok, no, I just missed it in the redirects.

I had:

```Redirect "/introducing-1-0" "https://sabnzbd.org/wiki/introducing-1-0"
Redirect "/introducing-0-7" "https://sabnzbd.org/wiki/introducing-1-0"```

Needed to be:

```Redirect "/introducing-1-0-0" "https://sabnzbd.org/wiki/introducing-1-0"
Redirect "/introducing-0-7-0" "https://sabnzbd.org/wiki/introducing-1-0"```

**Comment by shypike** [comment]
Jeff,

There's another one missing:
https://sabnzbd.org/wiki/configure-1-0
You get there when clicking Help in the Config overview page:
http://127.0.0.1:8080/sabnzbd/config/

kind regards
Con


2016-06-30 5:39 GMT+02:00 Jeff George <notifications@github.com>:

**Comment by Safihre** [comment]
@jeffgeorge bump ;)

**Comment by jeffgeorge** [comment]
Oh, hey, we've got that page too it just needs to be redirected also:

https://sabnzbd.org/wiki/configuration/1.0/configure

**Comment by jeffgeorge** [comment]
Fixed:

```
Redirect "/configure-1-0" "https://sabnzbd.org/wiki/configuration/1.0/configure"
```
