### ISSUE TITLE
new sherpa mini-package-manager for QNAP NAS!

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd.github.io#108]
Hi guys, 

Rather than go through the whole cloning thingy so I can generate a PR , can I ask someone to fix this at their end? 😉 

Relates to this page: https://github.com/sabnzbd/sabnzbd.github.io/blob/master/wiki/installation/install-nas.md

Sherpa is no-longer an "installer script" because it's evolved over the last couple of years and is now a "mini-package-manager" and is available for installation as a QNAP QPKG. ~~The existing URL is correct.~~

Cheers! 🤓

**Comment by OneCDOnly** [comment]
Actually, I'll give you the nice URL for sherpa instead of the community forum one:

[https://git.io/sherpa](https://git.io/sherpa)

**Comment by Safihre** [comment]
Done. You can also edit the file here on Github, it does the cloning/branching/PR'ing thing for you :)
