### ISSUE TITLE
Improve: Fedora and RHEL/CentOS/Scientific Linux RPM

### ISSUE THREAD

**Issue by no1knows** [sabnzbd/sabnzbd.github.io#11]
## URL: /wiki/installation/install-fedora-repo.html

Improvement:
Refer to the repos here: https://copr.fedorainfracloud.org/coprs/thecubic/SABnzbd/ which are actually updated for new versions.

**Comment by Safihre** [comment]
This link is already there:

> Alternative source
> Another package is maintained by user thecubic, he provides src and bin RPMs from CentOS 6 through Fedora Rawhide.

**Comment by Safihre** [comment]
I have reordered the page to give this repo more attention :)
