### ISSUE TITLE
Improve: Install SABnzbd on a NAS

### ISSUE THREAD

**Issue by Kurtbe** [sabnzbd/sabnzbd.github.io#119]
## URL: /wiki/installation/install-nas.html

Improvement:
I cannot provide the improvement, however the information currently given does not seem to coincide anymore with the current version of the Synology software.

**Comment by Safihre** [comment]
The steps written on SynoCommunity.com you mean?
In that case open an issue at https://github.com/SynoCommunity/spksrc/issues

**Comment by jcfp** [comment]
No response, closing.
