### ISSUE TITLE
Improve: Command Line Parameters

### ISSUE THREAD

**Issue by protogen** [sabnzbd/sabnzbd.github.io#12]
## URL: /wiki/advanced/command-line-parameters.html

Improvement:
In the description for the `--pid` option it states that the pid file name will be `sabnzbd_port.pid` (underscore before port), however the file name actually created is `sabnzbd-port.pid` (dash before port).

This is confirmed in the source code:
`DIR_PID = os.path.join(pid_path, 'sabnzbd-%s.pid' % port)`

**Comment by Safihre** [comment]
Thanks!
