### ISSUE TITLE
Improve: Install SABnzbd on a Netgear NAS

### ISSUE THREAD

**Issue by carravera** [sabnzbd/sabnzbd.github.io#120]
## URL: /wiki/installation/install-nas.html

Improvement:

is it possible to make a bin file installation for readynas OS4 X86 devices also?
There were some versions on https://rnxtras.com/add-ons/update/sabnzbd-1-2-0-all-readynas-platforms-79987 but i don't see any updates coming anymore.

If it's possible that would be great as i still use it for nzb downloading and sickbeard with sabnzbd integration. 

hope something is possible.

greetz.

**Comment by jcfp** [comment]
If you know of a properly supported up-to-date package for your NAS and find it's not listed on the wiki, please do tell us: we'd happy to include it. This issue tracker is not a place for requesting the sabnzbd developers to create such things from scratch though.

You might have better luck asking whoever created the packages you currently use, although it may not be a coincidence that updates there come to a halt at sabnzbd 2.3.9, the last version using python2.
