### ISSUE TITLE
Improve: High speed Downloading

### ISSUE THREAD

**Issue by bumbeen** [sabnzbd/sabnzbd.github.io#121]
## URL: /wiki/advanced/highspeed-downloading.html

Improvement:

fast.com link does not show accurate internet speed for users in hawaii. recommend xfinity or ookla

**Comment by jcfp** [comment]
Fast.com is preferred here because it's an isp-independent service, hosted by netflix. That means it can detect not only client-side issues (crappy wifi, driver issues) but also many forms of isp bandwidth throttling and long-distance network congestion.

As both netflix and usenet find themselves among the most commonly throttled services, fast.com provides a much more realistic picture than a speed test hosted locally and/or given preferential treatment by your own isp, such as both your recommendations.

**Comment by bumbeen** [comment]
I am able to pull 480mbps on usenet, but fast.com shows 38mbps down rate. Various other speed tests from far off locations will show 480mbps which is my line rate. just fast.com seems to be incorrect. Don't guess it matters much, the only people using sabnzbd are going to know better anyway

**Comment by jcfp** [comment]
Thanks for your feedback. Those numbers indicate your isp throttles netflix (albeit at a level where you're not going to notice when only streaming to a single device), but not usenet. Fast.com = netflix, which in turn uses akamai as its cdn; for them 480 mbit is a rounding error.

**Comment by bumbeen** [comment]
Nah, I get the same speed from fast.com when using vpn too. but if u know fast.com is likely to be throttled independently why suggest it as a speed test for sabnzbd XD

**Comment by jcfp** [comment]
> but if u know fast.com is likely to be throttled independently why suggest it as a speed test for sabnzbd XD

As explained before: we need realistic numbers on users' internet connections, throttling included; we couldn't care less about the empty promises of isp marketing departments. Many providers aren't exactly open let alone honest about their business practices, esp. in countries where effective network neutrality isn't legally enforced (such as the usa).

The vpn numbers only confirm your isp's throttling is behind the 38 mbit result you got earlier, not some limitation of fast.com.

**Comment by bumbeen** [comment]
VPN is showing that the connection between Hawaii and fast.com sucks which is why i opened the issue. It's not a limitation of fast.com but a limitation of using fast.com to determine connection speed for the purposes of using it with SABNZBD.

my Hawaii PC > My ISP > Hawaii - california fiber > fast.com = 30% throughput / usenet 100% Throughput
my Hawaii PC > My ISP > Hawaii VPN Ingress > Hawaii VPN Egress >Hawaii - California fiber >  Fast.com = 30% throughput / usenet 100% throughput
my Hawaii PC > My ISP > Hawaii VPN Ingress > Hawaii - California fiber >  socal VPN egress > fast.com = 100% throughput / usenet 100% Throughput

unless u think HMA VPN has a residential connection to spectrum for their hawaii VPN Egress idk why i get the results I do.

Potentially they are throttling it at a higher level which affects every connection to fast.com from hawaii. So given the fact netflix and fast.com are individually singled out for throttling, while usenet at least in my case is not, I get a very unrealistic number on my internet connection for the purpose of choosing sabnzbd speed options.
