### ISSUE TITLE
Improve: Special settings

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd.github.io#127]
## URL: /wiki/configuration/3.2/special.html

Improvement:
downloader_sleep_time - CPU sleep period that is some times added between reading data from the connections. Higher values may reduce CPU load but too high values will impact the download speed. A value of 0 should only be used if increasing the number of connections is not sufficient to get maximum speed. A value of 10 means 1 ms.

**Comment by Safihre** [comment]
I was going to change it later today, but to make changes to the website you can also simply make a PR here. The changes get automatically published to the website after merging. 😊
