### ISSUE TITLE
Quick fix to the wiki, installs old version 7.20 w/o this

### ISSUE THREAD

**Issue by TechJennings** [sabnzbd/sabnzbd.github.io#13]
## URL: /wiki/installation/install-ubuntu-repo.html

Improvement:

ubuntu 16.04 will throw an error upon usage of the command:
'add-apt-repository ppa:jcfp/ppa' w/ or w/o the sudo command/root account

you have to install:
apt-get install software-properties-common and then the add-apt-repository command will work

not sure what the deal is but it is what it is

If you miss the error that it throws back at you after 'add-apt-repository ppa:jcfp/ppa' and continue with the rest of the commands then it install an old version of SABNZBd (7.20) presumably from canonical's official repositories.

**Comment by shypike** [comment]
Thanks for the tip, fixed now.
The package allows adding of third-party repositories.
Apparently it's missing on server installations, possible also on desktops.
