### ISSUE TITLE
Improve: Install SABnzbdon a NAS

### ISSUE THREAD

**Issue by bigragu** [sabnzbd/sabnzbd.github.io#146]
## URL: /wiki/installation/install-nas.html

Improvement:Asustor please

**Comment by sanderjo** [comment]
@bigragu the meaning of a pull request is that **you** provide the improvement. 
If you're looking for help on Asustor, you could ask for help on the SABnzbd forum https://forums.sabnzbd.org/viewforum.php?f=2 Start by describing what you've done.
