### ISSUE TITLE
Improve: Configure

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#15]
## URL: /wiki/configuration/1.2/configure.html

Improvement:
`Posts on usernet are coded in the yEnc format, decoding this during the downloading using Python is not very efficient. Therefore we implemented this part in C for a big gain in performance. `

should be usenet not usernet.

then about yenc below.. may be late to even do this isnce sabyenc is coming but I have yenc 0.4 built for python 2.7.x on windows (32 and 64bit).. which shy/inp was supposed to put on sab's site so we can host/just include.
http://zoggy.net/yenc-0.4_py2.7.rar

**Comment by Safihre** [comment]
I put your compiled versions on the website a long time ago :) 
https://sabnzbd.org/wiki/installation/install-from-source-windows

**Comment by thezoggy** [comment]
oh gotcha, yeah didnt see it on the configure page when it was talking about yenc there..
