### ISSUE TITLE
Improve: How to make a portable installation

### ISSUE THREAD

**Issue by DoS007** [sabnzbd/sabnzbd.github.io#176]
## URL: /wiki/extra/howto-portable.html

Improvement:
portable.cmd isn't part of new standalone versions

**Comment by Safihre** [comment]
You are right, sorry about that.
Will be fixed in the next release.
You can download the file here: https://raw.githubusercontent.com/sabnzbd/sabnzbd/develop/portable.cmd

**Comment by DoS007** [comment]
@Safihre 
One more question: I renamed the `SABnzbd.exe` to `renamed_SABnzbd` so i don't click it unintentional. I edited the portable.cmd accordingly:
`@start "renamed_SABnzbd" /MIN %~dp0renamed_SABnzbd.exe -f %~dp0 %1 %2 %3 %4 %5 %6 %7 %8 %9
@exit`.

But that gives me an error "Cannot open self [...]". Why is that? That didn't happen with the old version I had (don't know which it was, i already overwrote it with the new version)?
