### ISSUE TITLE
Improve: Install SABnzbdon a NAS

### ISSUE THREAD

**Issue by CQuillinan** [sabnzbd/sabnzbd.github.io#182]
## URL: /wiki/installation/install-nas.html

Improvement:
readynas?

**Comment by CQuillinan** [comment]
do you have install for Netgear Readynas?

**Comment by sanderjo** [comment]
> do you have install for Netgear Readynas?

If you have questions, go to the SABnzbd forum.

If you have documentation to share, open a PR on this github
