### ISSUE TITLE
Improve: Install As A Unix Daemon

### ISSUE THREAD

**Issue by schabau** [sabnzbd/sabnzbd.github.io#206]
## URL: /wiki/installation/install-as-a-unix-daemon.html

Hi there,

it is unfortunate that sabnzbd still hasn't managed to provide a proper shutdown when sabnzbd is running as a daemon.
Putting the API key and possibly also the username and password in a file under /etc/init.d/ is "quick & dirty", but not a final state.

But that's not my topic for today.
They recommend a script in the WIKI under /etc/init.d/ with this line to stop sabnzbd.

`/usr/bin/wget -q --delete-after "http://HOSTADDRESS:PORT/sabnzbd/api?mode=shutdown&amp;apikey=ENTERAPIKEYHERE"`

This basically works quite well if you run it as a user. However, there can be problems if the script is called automatically when the PC/Server is shut down.
It can then happen that "--delete-after" is no longer executed and such files remain in / :

api?mode=shutdown&ma_username=XXX&ma_password=XXX&apikey=acdbXXX.tmp

The problem can be avoided by using the "--spider" option. The "--delete-after" option is then not necessary at all.

`/usr/bin/wget -q --spider "http://127.0.0.1:8080/sabnzbd/api?mode=shutdown&ma_username=XXX&ma_password=XXX&apikey=acdbXXX"`

With the "--spider" option, nothing is downloaded from wget, so nothing needs to be deleted. Possibly this can be mentioned in the WIKI.

But I still hope that there will be a reasonable implementation for the shutdown at sabnzbd at some point.

Many greetings
Detlef Paschke

**Comment by Safihre** [comment]
@jcfp @sanderjo What do you think?

**Comment by jcfp** [comment]
We should remove that script entirely and instead simply point to (or embed) the example [systemd service](https://github.com/sabnzbd/sabnzbd/blob/develop/linux/sabnzbd%40.service).

**Comment by sanderjo** [comment]
> it is unfortunate that sabnzbd still hasn't managed to provide a proper shutdown when sabnzbd is running as a daemon.

What problems?
And: on Unix, or on Linux?

I never have problems stopping the SABnzbd daemon on Ubuntu and Debian:

```
sander@brixit:~$ sudo service sabnzbdplus status
● sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
     Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
     Active: active (running) since Tue 2022-04-12 17:49:39 CEST; 1 day 20h ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 22 (limit: 9188)
     Memory: 545.5M
     CGroup: /system.slice/sabnzbdplus.service
             └─2712611 /usr/bin/python3 -OO /home/sander/git/sabnzbd/SABnzbd.py --daemon --pidfile /var/run/sabnzbdplus/pid --config-file /home/sander/.sabnzbd/sabnzbd.ini

apr 12 17:49:36 brixit systemd[1]: Starting LSB: SABnzbd+ binary newsgrabber...
apr 12 17:49:36 brixit sabnzbdplus[2712578]:  * Starting SABnzbd+ binary newsgrabber
apr 12 17:49:39 brixit sabnzbdplus[2712578]:    ...done.
apr 12 17:49:39 brixit systemd[1]: Started LSB: SABnzbd+ binary newsgrabber.
sander@brixit:~$
```

```
sander@brixit:~$ sudo service sabnzbdplus stop
```

```
sander@brixit:~$ sudo service sabnzbdplus status
● sabnzbdplus.service - LSB: SABnzbd+ binary newsgrabber
     Loaded: loaded (/etc/init.d/sabnzbdplus; generated)
     Active: inactive (dead) since Thu 2022-04-14 14:01:00 CEST; 1s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 3067240 ExecStop=/etc/init.d/sabnzbdplus stop (code=exited, status=0/SUCCESS)

apr 12 17:49:36 brixit systemd[1]: Starting LSB: SABnzbd+ binary newsgrabber...
apr 12 17:49:36 brixit sabnzbdplus[2712578]:  * Starting SABnzbd+ binary newsgrabber
apr 12 17:49:39 brixit sabnzbdplus[2712578]:    ...done.
apr 12 17:49:39 brixit systemd[1]: Started LSB: SABnzbd+ binary newsgrabber.
apr 14 14:00:59 brixit systemd[1]: Stopping LSB: SABnzbd+ binary newsgrabber...
apr 14 14:00:59 brixit sabnzbdplus[3067240]:  * Stopping SABnzbd+ binary newsgrabber
apr 14 14:01:00 brixit sabnzbdplus[3067240]:    ...done.
apr 14 14:01:00 brixit systemd[1]: sabnzbdplus.service: Succeeded.
apr 14 14:01:00 brixit systemd[1]: Stopped LSB: SABnzbd+ binary newsgrabber.
sander@brixit:~$

```

**Comment by sanderjo** [comment]
Ah, @schabau is referring to https://sabnzbd.org/wiki/installation/install-as-a-unix-daemon ?

I've never used that. So, @jcfp , are you proposing to just delete that wiki page?
