### ISSUE TITLE
Improve: Installing Multicore Par2

### ISSUE THREAD

**Issue by ElHupeke** [sabnzbd/sabnzbd.github.io#21]
## URL: /wiki/installation/multicore-par2.html

Improvement:

Tekst correction commands:

git clone https://github.com/jkansanen/par2cmdline-mt.git
cd par2cmdline-mt
aclocal
automake --add-mising
autoconf
./configure
make
make install

automake --add-mising, should be automake --add-missing ?

**Comment by Safihre** [comment]
Thanks, fixed! 👍
