### ISSUE TITLE
Improve: Ubuntu PPA Repository

### ISSUE THREAD

**Issue by pawelgalecki** [sabnzbd/sabnzbd.github.io#217]
## URL: /wiki/installation/install-ubuntu-repo.html

Improvement:

sudo add-apt-repository ppa:jcfp/nobetas
sudo apt-get update ~~&& sudo apt-get dist-upgrade~~
sudo apt-get install sabnzbdplus

Seriously? Why dist-upgrade? Do I really need to upgrade my kernel and nvidia-drivers to install sabnzbd?

**Comment by Safihre** [comment]
@jcfp I also wonder why that step is needed?

**Comment by jcfp** [comment]
It ensures the target system is up-to-date, so I have a stable baseline to work with and can exclude a potential source of trouble. Obviously I couldn't care less about nvidia-drivers and the likes but experience teaches there's plenty of newbies that literally didn't update anything in years - including python itself and core system tools (apt, dpkg, systemd, etc.).
