### ISSUE TITLE
legacy wiki

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#228]
thoughts on us retiring sab 2.x and older from wiki.
> sab 2.3.9 was released on May 24, 2019 

Could roll all the pre sab 3.x to one legacy wiki to target 2.3.9's last wiki instance as a catch all and warn that if your seeing it you are using an outdated/end of life version and to upgrade (but still keep wiki bits for those that actually need it from that time).

This would allow to cleanup quite a bit of wiki pages/redirects and make our jenkyll builds a bit faster..

**Comment by Safihre** [comment]
Where do we still have 2.x stuff then? I thought I had all long removed it?

**Comment by thezoggy** [comment]
When run Jekyll for the wiki it generates 0.7.x/1.x/2.x and so on config sections and then various legacy old school wiki pages before the universal config days

**Comment by Safihre** [comment]
Those are just the redirects to the Deprocated page. The pages are empty.

**Comment by Safihre** [comment]
https://github.com/sabnzbd/sabnzbd.github.io/blob/master/wiki/configuration/deprecated.html

**Comment by thezoggy** [comment]
Jekyll takes about 48s to build our wiki on any change..  is it that slow for you as well?

**Comment by Safihre** [comment]
Yes, but then I just set it to watch changes and then it's not so slow on updates. 
You can try and remove the deprecated page and see if that speeds things up?
Maybe the source is something else.

**Comment by thezoggy** [comment]
when it builds the wiki initially or after any change, it re-gens the whole site which includes the 0.7/1.x/2.x/3.x pages:
![explorer_2022-08-30_19-54-39](https://user-images.githubusercontent.com/500882/187569439-dde3c641-4d4b-4f5f-867a-d1b965db2002.png)

can see that the READ process takes the longest, and redirect hits 192 times when profiled
![cmd_2022-08-30_19-53-08](https://user-images.githubusercontent.com/500882/187569281-8512db07-5a9c-4958-a3ee-897cfa5a1398.png)

**Comment by thezoggy** [comment]
> Yes, but then I just set it to watch changes and then it's not so slow on updates. You can try and remove the deprecated page and see if that speeds things up? Maybe the source is something else.

when i have it set to watch changes, it takes another ~48s to update. i don't recall it being this slow in the past.. i'm using the same command I did previously: `jekyll serve -i --host 0.0.0.0`

now I will say, this repo is on a normal mechanical drive rather than on an ssd, but wouldn't think it should be making that much of a difference...

**Comment by thezoggy** [comment]
dropping redirect plugin from _config.yaml
```
plugins:
  - jekyll-redirect-from
```

only barely helped:
```
Build Process Summary:

| PHASE      |    TIME |
+------------+---------+
| RESET      |  0.0001 |
| READ       | 45.7670 |
| GENERATE   |  0.0000 |
| RENDER     |  0.0410 |
| CLEANUP    |  0.1256 |
| WRITE      |  0.0349 |
+------------+---------+
| TOTAL TIME | 45.9686 |
```

did find some stuff about .jekyll-cache added in v4 and that you are supposed to exclude it in jekyll + gitignore.. added that to my recent pull request but still doesnt sadly speedup anything

**Comment by thezoggy** [comment]
I've been using jekyll 4.2.2, to test I went ahead and installed jekyll 3.9.2 and tried running with that

`gem install jekyll -v 3.9.2`
`jekyll _3.9.2_ serve -i --host 0.0.0.0 --profile`

sadly no help
```
done in 47.738 seconds
```

**Comment by Safihre** [comment]
@thezoggy What were the results?

**Comment by thezoggy** [comment]
completely forgot :x had been traveling for work and got covid..  but ill dig this back up

**Comment by Safihre** [comment]
I removed all <3.0.0.

**Comment by thezoggy** [comment]
just to note, pulled this update and tried and sadly no improvements :/

```
D:\sabnzbd.github.io>jekyll build --profile
Configuration file: D:/sabnzbd.github.io/_config.yml
            Source: D:/sabnzbd.github.io
       Destination: D:/sabnzbd.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...

Build Process Summary:

| PHASE      |    TIME |
+------------+---------+
| RESET      |  0.0001 |
| READ       | 47.5596 |
| GENERATE   |  0.0483 |
| RENDER     |  0.8765 |
| CLEANUP    |  0.0789 |
| WRITE      |  0.7484 |
+------------+---------+
| TOTAL TIME | 49.3118 |
```
