### ISSUE TITLE
Add page about keyboard shortcuts

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd.github.io#235]
- [ ] We don't have any info about them.
- [ ] We should also add a link to this page in the application.

**Comment by sanderjo** [comment]
Some notes

> Added keyboard shortcuts (Pause, Add, Status, Config).

P, A, S, C

From @thezoggy 

> Added shortcuts to navigate queue/history pagination:
> 
> shift+up -- first page
> shift+down -- last page
> shift+left -- previous page
> shift+right -- next page

... but that does not work for me, nor without shift

**Comment by Safihre** [comment]
Yeah I also noticed that and saw some user on the forums also asking this. @thezoggy does it only work with Tabbed layout?

**Comment by thezoggy** [comment]
works for me in tabbed and non tab. just have to enable the status > use shortcuts option. (and refresh page if toggling the shortcuts on)

**Comment by thezoggy** [comment]
i see the issue... when switching to non tabbed layout, sometimes the history 'tab' is active which is why it works. but sometimes the queue tab is 'active' which is when it doesnt work.

for tabbed layout, i was targetting only when the history tab is active so were not changing the pagination erroneously.

**Comment by Safihre** [comment]
Hmmm, difficult. Why would it be chaos if it changes both queue and history?
I've seen people with large queues and no history, or the other way around with a lot of history and almost no queue (like me).

**Comment by thezoggy** [comment]
problem is that we always apply active to one or the other. which logically makes sense and if we bind key commands to it, it works well for tabbed not so well for untabbed as noted. so lets say we just do both, which then on untabbed they only really see whatever one they 'need' as the one that isnt paginated they wouldnt see anything from it. 

the chaos then is seen on the tabbed version where your changing both and not just the active one. but i should be able to target something thats dictating its tabbed to fix that..
