### ISSUE TITLE
Improve: SABnzbd and SSL/TLS security

### ISSUE THREAD

**Issue by dny238** [sabnzbd/sabnzbd.github.io#238]
## URL: /wiki/advanced/certificate-errors.html

Improvement:
These errors can also occur if the TLS version of the server is below the minimum. Currently SABnzbd requires 1.3, but if you go into the settings you can allow older TLS versions like 1.2 with this option 'allow_old_ssl_tls ( off )'

**Comment by Safihre** [comment]
We only require 1.2 and above, not 1.3.

**Comment by dny238** [comment]
Hrm, I'm trying to troubleshoot why it was failing, with that option on it stops failing. External sources say I have servers with TLS 1.2 and 1.3 that fail, now that I look closer. 

[Example](https://www.appelboor.com/cgi-bin/check_newsserver.py?server=news.vipernews.com)

Got advice on how to check why my windows system thinks they are failing? Looking for a local cert checker.

**Comment by puzzledsab** [comment]
news.vipernews.com works for me with allow_old_ssl_tls off. "Connected using TLSv1.2 (AES128-SHA)", no cipher set by me. Which SABnzbd version are you using?

**Comment by thezoggy** [comment]
what python your using and openssl may dictate what tls options you have available... then what the far side accepts. so you could want tls 1.3 but may not be an option on the far side. or you might be using legacy openssl that might not have tls 1.3. or your tunneling it through a proxy that may be messing up whats available. 

you can check manually via doing something like:
https://blog.toshima.ru/2020/01/06/check-supported-tls-version.html
