### ISSUE TITLE
sourceforge - decom/update

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#24]
Per: https://sabnzbd.org/wiki/contact
>  SourceForge.net is our distribution platform. 

This is no longer true.. so we prob should update it to reflect GH now.. 

Now with that said, there is still benefit for having sourceforge as others that always went this route to get updates/discover through it... So maybe we should still put the non-beta's here (thus we need to add 1.2.x/2.x) and then just nuke the beta folder? Also we should prob add verbiage to direct people from SF to GH.

**Comment by Safihre** [comment]
@shypike, what to do?

**Comment by Safihre** [comment]
@shypike Ping ;)

**Comment by Safihre** [comment]
Added 2.1.0 so anyone downloading it there will have a 2.x version, to make sure we retain control.
