### ISSUE TITLE
Improve: SSL Ciphers

### ISSUE THREAD

**Issue by animetosho** [sabnzbd/sabnzbd.github.io#243]
## URL: /wiki/advanced/ssl-ciphers.html

Improvement:  
The page recommends `AES128-SHA`, but it's likely less optimal compared to just `AES128` (at least for CPUs with AES acceleration).

Explanation: https://www.reddit.com/r/usenet/comments/bk5zhl/nzbget_v21_released/emelgdg/

Newer CPUs do have SHA1 hardware acceleration, which may change figures somewhat (haven't tested), but I think AES128-SHA forces AES into (comparatively slow) CBC mode, so I can't imagine it being any faster than GCM modes.  
The exception may be on CPUs without AES acceleration.

**Comment by Safihre** [comment]
I modified it!

**Comment by Safihre** [comment]
Updated!
