### ISSUE TITLE
Improve: General - MB and Mb are not the same.

### ISSUE THREAD

**Issue by blckassassin** [sabnzbd/sabnzbd.github.io#277]
## URL: /wiki/configuration/4.0/general.html

Improvement:
 
Regarding the section Tuning with the header Maximum line speed it states the following:

> Set how fast your internet connection is, in bytes/sec.
> NOTE If you have an ISP-speed of 10Mbit/sec, you should enter 1MB/s here.

Mbit and MB are not the same, Mbit is 1/8 of a MB.  I believe what is meant is the following:

> Set how fast your internet connection is, in bytes/sec.
> NOTE If you have an ISP-speed of 10Mbytes/sec, you should enter 1MB/s here.

If necessary a link to a Mb to MB convertor could be provided if users know their speed in bytes but not in bits.  Such as this one https://www.gbmb.org/mbit-to-mb

**Comment by sanderjo** [comment]
No. It is meant as it's written. For simplicity and taking into account applications layer versus network layer, a factor of 10 is used.
