### ISSUE TITLE
Improve: Folder Setup

### ISSUE THREAD

**Issue by d0t1q** [sabnzbd/sabnzbd.github.io#29]
## URL: /wiki/advanced/directory-setup.html

Improvement:
Administrative directory admin_dir: 
Should contain the following line
Vista/Win7/Win10	%userprofile%\AppData\Local\sabnzbd\admin

Log directory log_dir: 
Should contain the following line
Vista/Win7/Win10	%userprofile%\AppData\Local\sabnzbd\logs

**Comment by Safihre** [comment]
Fixed!
