### ISSUE TITLE
Improve: Special settings

### ISSUE THREAD

**Issue by Kvothe1970** [sabnzbd/sabnzbd.github.io#30]
## URL: /wiki/configuration/2.1/special.html

Improvement:

The option: par2_multicore ( on ) available in version 2.1.0 [443efb5]
is missing from the Wiki.

**Comment by Safihre** [comment]
Re-added! With the note that it will be removed in 2.2.0 (if all goes well) and that it only applies to Windows/macOS.

**Comment by Kvothe1970** [comment]
Thank you kindly!
