### ISSUE TITLE
Improve: Duplicate detection

### ISSUE THREAD

**Issue by ChrisWeiss** [sabnzbd/sabnzbd.github.io#305]
## URL: /wiki/extra/duplicate-detection.html

Improvement:
It should be specifically called out that duplicate detection does not _prioritize_ size, resolution, or bitrate. It is... alphabetical?

Actually linking to the GuessIt documentation would also be helpful (https://pypi.org/project/guessit/)

**Comment by Safihre** [comment]
It probably should be mentioned indeed. And that if you want such features they should use Sonarr/Radarr/etc.
The GuessIt documentation doesn't really say much about how it actually parses stuff, only for Sorting it's relevant I think.

**Comment by ChrisWeiss** [comment]
I do use the various 'Arr' apps, but I do quite a lot of manual searching as well. The 'arr' apps do a great job of handling quality decisions so I don't need to think about them.

**Comment by Safihre** [comment]
So what changes should we make to the documentation?

**Comment by ChrisWeiss** [comment]
On reading it again, I guess it is pretty explicit that the _first_ item in the queue is DL'd and anything after is a dupe.
