### ISSUE TITLE
Improve: NZB Sources

### ISSUE THREAD

**Issue by Nzb-Tortuga** [sabnzbd/sabnzbd.github.io#31]
## URL: /wiki/introduction/nzb-sources.html

Improvement:
can you please add this indexer https://www.nzb-tortuga.com/

to this page  https://sabnzbd.org/wiki/introduction/nzb-sources

**Comment by Safihre** [comment]
Sure, can you give me the information that we need to add it to the table? 
	_Code Base?
Registrations?
Free Account Limits?_

**Comment by Nzb-Tortuga** [comment]
Thank you so much 

sure its

Site, https://www.nzb-tortuga.com/
Code Base Newznab
Registrations Open
Free Account Limits - unlimated full 7 day access
