### ISSUE TITLE
Improve: Install SABnzbd on a NAS

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#321]
## URL: /wiki/installation/install-nas.html

just tossing this here we can update qnap section

Was talking to someone on discord, they use qnap and get sab from 'qnapclub' but actually looks like they are no longer and now has outdated stuff.
Found that qnap peeps look to use myqnap: `https://www.myqnap.org`

per reddit:
>  Qnapclub was hosted in Belgium and manager kicked the main dev (qoolbox) .. So he built with a French team a new repo and a discord chat for support and inquiries... There are no relationship between qnapclub and myqnap. Org... All devs moves there...

**Comment by Safihre** [comment]
@onecdonly thoughts?

**Comment by OneCDOnly** [comment]
Yes, MyQNAP should certainly be added as an installation source. QNAPClub has been discontinued.
