### ISSUE TITLE
Improve: New features and changes

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#34]
## URL: /wiki/new-features-and-changes.html

need to redo this page so people can see why they should upgrade from 0.7.x->1.x->2.x etc

maybe something like a nice change log page showing main features/bugs addressed

**Comment by thezoggy** [comment]
reason i mention this is because this is one of the urls in the sab irc channel... so it gets a lot of exposure

**Comment by Safihre** [comment]
This page is not linked from anywhere else anymore.
How do we remove it from IRC?

We can re-instate it, if somebody feels like updating the text?

**Comment by thezoggy** [comment]
i can update the irc title, but its nice to show people at a high level why they should update.. ill update the text. i just added this as a reminder
