### ISSUE TITLE
MBs bijwerken

### ISSUE THREAD

**Issue by DeeJeeJan** [sabnzbd/sabnzbd.github.io#346]
## URL: /wiki/configuration/4.3/special.html

Improvement:Bij het starten van dit programma ben ik steeds verplicht de MBs in te voeren, kan dat ook anders?

**Comment by Safihre** [comment]
Dit is geen plek voor vragen, maar voor verbeteringen aan de website.

Vragen kun je stellen op ons forum, Discord en Reddit.

Kort antwoord lijkt erop dat je de Limiet steeds moet instellen? Dat doe je via Advanced Options op de General pagina van de Config.
