### ISSUE TITLE
Improve: NZB Sources

### ISSUE THREAD

**Issue by r33gan** [sabnzbd/sabnzbd.github.io#35]
## URL: /wiki/introduction/nzb-sources.html

Improvement:

Add https://fastnzb.com

**Comment by Safihre** [comment]
Sure, can you give us the extra info for the table?

**Comment by r33gan** [comment]
Code base nZEDb/Custom
Registrations: Open
No limits

**Comment by Safihre** [comment]
So there is both fastnzb.info and fastnzb.com? Interesting
