### ISSUE TITLE
Improve: Fedora and RHEL/CentOS/Scientific Linux RPM

### ISSUE THREAD

**Issue by naveci** [sabnzbd/sabnzbd.github.io#37]
## URL: /wiki/installation/install-fedora-centos-rhel.html

Improvement:

I've a bit of a list of things that are inaccurate.
* Step 2: the li.nux.ro/repos sites with a command for centos 7 does not work.
`Retrieving http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
warning: /var/tmp/rpm-tmp.wDlUby: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)`
I've decided to skip, since I had epel-release active anyway

* The dependencies are missing Python-Cheetah

* Step 7 has a command (cat) in the first line of the code. Copying the text obviously does not work. Point being, this is not noob friendly

**Comment by Safihre** [comment]
Maybe you can edit the text and send a Pull-Request?
https://github.com/sabnzbd/sabnzbd.github.io/edit/master/wiki/installation/install-fedora-centos-rhel.html

**Comment by naveci** [comment]
Done. First time working on git. So I hope you guys got the pull request

**Comment by Safihre** [comment]
👍
