### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd.github.io#4]
Don't we want some analytics on the page? Like Google Analytics.
Or CloudFlare does that?

**Comment by jeffgeorge** [comment]
Cloudflare provides some anonymized traffic stats, but nothing approaching what Google Analytics provides. I'm not sure how much we care about in-depth tracking, though. @shypike, thoughts?

**Comment by Safihre** [comment]
I would be interested which pages of the Wiki people visit and how they flow through the pages. To see what we could improve in the information :)

**Comment by Safihre** [comment]
Would you guys mind if I add Google Analytics for a month or so to get some insight into this? After this I can remove it again.

**Comment by Safihre** [comment]
Based on these stats I have updated many of the Wiki pages this weekend, fine-tuning all the content:

_(/downloads.html -> when people click the update link in SABnzbd, /downloads is when they follow the link on sabnzbd.org)_
![image](https://cloud.githubusercontent.com/assets/5703454/16902855/5ca4866e-4c6c-11e6-8bbe-c12886c3636d.png)
