### ISSUE TITLE
Improve: Categories

### ISSUE THREAD

**Issue by OneCDOnly** [sabnzbd/sabnzbd.github.io#41]
## URL: /wiki/configuration/2.3/categories.html

Improvement:
There's a minor grammatical error in the 'Notes' section. 

"_Instead of listing all possible categories, you may simple use TV*._"

should probably read as:

"_Instead of listing all possible categories, you may simply use TV*._"

Thank you.

**Comment by Safihre** [comment]
Thanks!
If you feel like spell-checking the whole wiki I can give you write access 😉

**Comment by OneCDOnly** [comment]
Oh, yes please! ;)
