### ISSUE TITLE
Improve: Install SABnzbd on a NAS

### ISSUE THREAD

**Issue by flowy0** [sabnzbd/sabnzbd.github.io#42]
## URL: /wiki/installation/install-nas.html

Improvement:

Can a package be compiled for ASUS NAS?

**Comment by Safihre** [comment]
As far as I understand the QNAP packages also work for Asus? Don't have one myself.

**Comment by sanderjo** [comment]
I have no ASUS NAS, so this is just a guess: https://www.asustor.com/app_central/app_detail?id=98&type=

**Comment by flowy0** [comment]
i was looking for a package for sabyenc
https://sabnzbd.org/wiki/installation/sabyenc.html

**Comment by Safihre** [comment]
Indeed the package is outdated for the recent SABnzbd release.. @clinton-hall, maybe he has time? 

Is there a way for you to SSH into the device and run the install commands?
