### ISSUE TITLE
Improve: SSL Ciphers

### ISSUE THREAD

**Issue by activematrix** [sabnzbd/sabnzbd.github.io#56]
## URL: /wiki/advanced/ssl-ciphers.html

Improvement:
Debian Stretch includes OpenSSL 1.1.0f, which has disabled RC4-MD5 cyphers.  Manually recompiling OpenSSL with the “enable-weak-ssl-ciphers” flag.

**Comment by sanderjo** [comment]
Do you mean: https://sabnzbd.org/wiki/advanced/ssl-ciphers says 

> Setting SSL Ciphers to the following value will lower encryption strength, increase performance (download speed) and is supported by virtually all nesservers:
> 
> RC4-MD5

... but RC4-MD5 is not available on Debian Stretch?

**Comment by activematrix** [comment]
It's not just Debian Stretch, it is disabled in all versions of OpenSSL after 1.0.2f.

` Changes between 1.0.2f and 1.0.2g [1 Mar 2016]

  * Disable weak ciphers in SSLv3 and up in default builds of OpenSSL.
    Builds that are not configured with "enable-weak-ssl-ciphers" will not
    provide any "EXPORT" or "LOW" strength ciphers.
    [Viktor Dukhovni]`

The only way to enable RC4-MD5 in newer versions of OpenSSL is to manually recompile it with a "enable_weak_ssl_ciphers" flag set.  This will have to be redone any time OpenSSL updates.  

I don't know if it is really necessary at this point, since my Raspberry Pi 2 can process about 20Mb/s with most AES-128 cyphers, and that's pretty low powered.  I would recommend that this whole page be deprecated.

**Comment by activematrix** [comment]
The issue is not just with Debian Stretch, it is with OpenSSL 1.0.2g and newer.  
` Changes between 1.0.2f and 1.0.2g [1 Mar 2016]

  * Disable weak ciphers in SSLv3 and up in default builds of OpenSSL.
    Builds that are not configured with "enable-weak-ssl-ciphers" will not
    provide any "EXPORT" or "LOW" strength ciphers.
    [Viktor Dukhovni]`

The only way around it is to manually compile OpenSSL with "enable-weak-ssl-ciphers" flag set.  This would most likely need to be done again any time OpenSSL updated.  

I recommend that you consider deprecating this page entirely, because as paople upgrade their linux distros or their existing distros push newer versions of OpenSSL, many people are going to start having this issue.

**Comment by sanderjo** [comment]
> The issue is not just with Debian Stretch, it is with OpenSSL 1.0.2g and newer.
> Disable weak ciphers in SSLv3 and up

> I recommend that you consider deprecating this page entirely

I agree; the goal of that wiki page seems to be downgrading to RC4-MD5, which is regarded unsafe by OpenSSL. In other words: a DTO (Defeating The Object) as it's fake security.

@Safihre Do you agree to delete the wiki page?

**Comment by sanderjo** [comment]
On my old Ubuntu 14.04 (with OpenSSL 1.0.1f 6 Jan 2014), default is:

```
2018-02-15 22:26:14,999::INFO::[newswrapper:122] 6@newsreader3.eweka.nl: Connected using TLSv1/SSLv3 (AES128-SHA)
2018-02-15 22:26:15,011::INFO::[newswrapper:122] 4@newsreader3.eweka.nl: Connected using TLSv1/SSLv3 (AES128-SHA)
```

... and I could still specify RC4-MD5

```
2018-03-01 11:03:04,739::INFO::[newswrapper:122] 3@newsreader3.eweka.nl: Connected using TLSv1/SSLv3 (RC4-MD5)
2018-03-01 11:03:04,740::INFO::[newswrapper:122] 1@newsreader3.eweka.nl: Connected using TLSv1/SSLv3 (RC4-MD5)
```

I will update with result from Ubuntu 17.10. I wonder what will happen ...

**Comment by Safihre** [comment]
@activematrix This is not only intended for Pi users, but actually also for our Windows users (which are at least 5x more than Linux users) that have a very fast connection. They still want "sort of" SSL security, but also use their full (gigabit) connection.
Besides those few Linux distro's all other platforms with the majority of users (Windows/macOS/Synology NAS/QNAP NAS) are still on 1.0.x and will probably stay there unless Python updates that. But it seems Python has decided to keep the 2.7.x releases on 1.0.x since 2.7.x is soon end-of-life.

So it doesn't seem like a good idea to delete, but we could explain more that it can also be used to force stronger ciphers.

**Comment by thezoggy** [comment]
can confirm that ubuntu 16.x openssl no longer has RC4-MD5
---
```
openssl version
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1b  26 Feb 2019)
```
```
openssl ciphers RC4-MD5
Error in cipher list
140339583956736:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2549:
```
sort md5 ciphers from strongest to weakest:
```
openssl ciphers -v "LOW::MD5:@STRENGTH"
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
NULL-MD5                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=MD5 
```


while ubuntu 14.x
---
```
openssl version
OpenSSL 1.0.1f 6 Jan 2014
```
```
openssl ciphers RC4-MD5
RC4-MD5
```
sort md5 ciphers from strongest to weakest:
```
 openssl ciphers -v "LOW::MD5:@STRENGTH" 
ADH-RC4-MD5             SSLv3 Kx=DH       Au=None Enc=RC4(128)  Mac=MD5 
RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5 
EDH-RSA-DES-CBC-SHA     SSLv3 Kx=DH       Au=RSA  Enc=DES(56)   Mac=SHA1
EDH-DSS-DES-CBC-SHA     SSLv3 Kx=DH       Au=DSS  Enc=DES(56)   Mac=SHA1
ADH-DES-CBC-SHA         SSLv3 Kx=DH       Au=None Enc=DES(56)   Mac=SHA1
DES-CBC-SHA             SSLv3 Kx=RSA      Au=RSA  Enc=DES(56)   Mac=SHA1
EXP-RC2-CBC-MD5         SSLv3 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
EXP-ADH-RC4-MD5         SSLv3 Kx=DH(512)  Au=None Enc=RC4(40)   Mac=MD5  export
EXP-RC4-MD5             SSLv3 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
NULL-MD5                SSLv3 Kx=RSA      Au=RSA  Enc=None      Mac=MD5 
```
