### ISSUE TITLE
Improve: NZB Sources

### ISSUE THREAD

**Issue by iandol** [sabnzbd/sabnzbd.github.io#6]
## URL: /wiki/introduction/nzb-sources.html

Improvement: Hi, as I understand it DOGnzbs is not a lifetime subscription, but it is annual $15 and you must pay a $10 credit card transaction fee. And it is currently open for trial registration (10 days of use).

**Comment by Safihre** [comment]
Will update to reflect it's per year. However, usually it's not open for registrations, only very rarely. If it stays open, will change the text.
