### ISSUE TITLE
host_whitelist autopopulated with just <hostname>

### ISSUE THREAD

**Issue by djpbessems** [sabnzbd/sabnzbd.github.io#61]
The new feature host_whitelist is currently automatically populated with `<hostname>`, so that requests to http://server:8080/ still work.
This should probably be expanded to `<hostname>, <hostname>.<searchsuffix>`, so that requests to http://server.domain:8080/ still work.

**Comment by sanderjo** [comment]
AFAIK the whole goal is to avoid exactly that; if you would accept server<.anydomain> then you re-enable DNS-hijacking, because <anydomain> can be evildomain.com, and thus hostname.evildomain.com can point to 127.0.0.1.

For example, if someone named his system "safihre", this is the DNS-hijack in place (real-life DNS entry):

$ host safihre.appelboor.com
safihre.appelboor.com has address 127.0.0.1

**Comment by Safihre** [comment]
Agreed with @sanderjo. 
How would we know this `searchsuffix`?

**Comment by djpbessems** [comment]
I don't mean the client side searchsuffix (searchdomain in linux), but the one on the host. It is a value part of the configuration of the networkinterface on both Windows and Linux.
`$ hostname -d` or maybe `$ grep search /etc/resolv.conf`

Right now accessing sabnzbd with an FQDN (pretty common in setups where there is a local domain/ActiveDirectory) is broken unless you manually whitelist the searchdomain/searchsuffix; I haven't encountered any other service with a builtin webinterface (or even any webserver like apache/nginx/lighttpd/IIS) that breaks when using an FQDN to access it.

**Comment by sanderjo** [comment]
Ah, now I understand what you mean.

N=1 analysis:
On my Ubuntu at home: "hostname -d" is empty
On my Ubuntu VPS: "hostname -d" gives a domain which is different than I use to access SAB: VPS-provider-domain versus my own domain.

Then: SAB is crossplatform, so which python calll gives the searchdomain info on Windows & MacOS & Linux?

To me it looks a niche case to solve "fill out FQDN once" with probably a lot of code.

**Comment by djpbessems** [comment]
Actually, I have zero experience with python, so I guess that'd be a deadend :)

Searching the web gives results like these:
https://p.itch.fyi/UI3bLM
but nothing for Linux

Oh well...

**Comment by sanderjo** [comment]
> Oh well...

Yeah. :-(
