### ISSUE TITLE
Improve: Install from source - C version of NameMapper on Windows

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd.github.io#62]
## URL: /wiki/installation/install-off-modules.html

Improvement:

On windows you get the following warning:

```
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "
```

The C version of `NameMapper` for Windows is not included in Cheetah v2 (which is required by SABnzbd) but is included in Cheetah v3.

Having the user `pip instal cheetah3` in addition to `pip install cheetah` will get them the optional C version of `NameMapper` without having to compile it or get it from an alternate source.

**Comment by Safihre** [comment]
NameMapper isn't used for Sab, so it's not really a problem. But I can change it to indeed download `cheetah3` if that's better.

**Comment by Safihre** [comment]
I used your feedback and tried to make it more clear that `install-off-modules` is only for Linux.
Now also references `cheetah3` instead of `cheetah`.

**Comment by sanderjo** [comment]
I still get this with SAB3 from source on Windows. And looking at the more recent https://github.com/CheetahTemplate3/cheetah3/issues/7#issuecomment-449944328 it's not solved?

```
C:\Users\sande\AppData\Local\Programs\Python\Python38\lib\site-packages\Cheetah\Compiler.py:1629: UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with compiled C version of NameMapper.
  warnings.warn(
```

Details:

```
C:\Users\sande\git\sabnzbd>SABnzbd.py
2020-03-15 13:58:57,673::INFO::[SABnzbd:1095] --------------------------------
2020-03-15 13:58:57,674::INFO::[SABnzbd:1096] SABnzbd.py-3.0.0-develop (rev=unknown)
2020-03-15 13:58:57,677::INFO::[SABnzbd:1097] Full executable path = C:\Users\sande\git\sabnzbd\SABnzbd.py
2020-03-15 13:58:57,679::INFO::[SABnzbd:1103] Platform = Windows-10-10.0.18362-SP0 (win64)
2020-03-15 13:58:57,681::INFO::[SABnzbd:1108] Python-version = 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
2020-03-15 13:58:57,682::INFO::[SABnzbd:1109] Arguments = C:\Users\sande\git\sabnzbd\SABnzbd.py
```

**Comment by Safihre** [comment]
Because Cheetah hasn't provided binaries for Python 3.8 at PyPi: https://pypi.org/project/Cheetah3/#files

**Comment by sanderjo** [comment]
> Because Cheetah hasn't provided binaries for Python 3.8 at PyPi: https://pypi.org/project/Cheetah3/#files

"Cheetah3-3.2.4-**cp37**-cp37m-win_amd64.whl" means for python 3.7, so with Python 3.7 no more error message?

**Comment by Safihre** [comment]
Yes.
