### ISSUE TITLE
Improve: Install from source - subprocessww

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd.github.io#63]
## URL: /wiki/installation/install-off-modules.html

Improvement:

Add `pip install subprocessww` to install instructions.

**Comment by Safihre** [comment]
It's already there, just should have read the start of that page ;)
https://sabnzbd.org/wiki/installation/install-from-source-windows

**Comment by labrys** [comment]
Reply oops I was just reading the regular install from source, lol.
