### ISSUE TITLE
Improve: Ubuntu PPA Repository

### ISSUE THREAD

**Issue by jeff2001** [sabnzbd/sabnzbd.github.io#67]
## URL: /wiki/installation/install-ubuntu-repo.html

Improvement: Include a step for enabling universe + multiverse repos to prevent unmet dependencies on newer versions of ubuntu

**Comment by Safihre** [comment]
@sanderjo / @jcfp could one of you add this? :)

**Comment by sanderjo** [comment]
@jeff2001 ... how do you enable universe + multiverse? How would you describe it to users?

**Comment by jeff2001** [comment]
@sanderjo 
sudo add-apt-repository multiverse
sudo add-apt-repository universe

Not sure how to describe it besides a repository required to meet all dependencies
I found reference to it in this post after hours of frustration and reinstalls of ubuntu server
-> https://forums.sabnzbd.org/viewtopic.php?f=16&t=387&hilit=Unofficial+Ubuntu+repository+for+SABnzbd 

As far as I understand this is for newer versions only and that some desktop versions already have those repos by default

**Comment by jeff2001** [comment]
Was that ubuntu desktop? I was on server so it's much slimmer. I didn't try with just one. I think as long as there is some sort of comment that they may be required for some installations would be great so that if people run into the problems following the default guide there is some sort of way forward saving figuring it out oneself

**Comment by sanderjo** [comment]
No, on a Ubuntu docker, so my guess is Server.

**Comment by jcfp** [comment]
Most dependencies of sab are in _universe_ on Ubuntu, so it definitely needed. Ubuntu's _main_ is just the core of the OS and the most important utils for server and desktop; everything else is 'community maintained' and thus in universe/multiverse.

Using add-apt-repository is probably the simplest and safest way for newbies but rather heavy for what amounts to editing a single line in apt's sources.list.

**Comment by sanderjo** [comment]
OK, I'll put it in the Wiki. Thanks, @jeff2001

**Comment by sanderjo** [comment]
OK ... done ... probably needs some to propagate to https://sabnzbd.org/wiki/installation/install-ubuntu-repo

**Comment by sanderjo** [comment]
@jcfp 
Is the part on sabyenc in https://sabnzbd.org/wiki/installation/install-ubuntu-repo still needed? I believe you have moved sabyenc to your "ppa:jcfp/ppa"? So no need anymore for "ppa:jcfp/sab-addons"?

**Comment by jcfp** [comment]
@sanderjo no such move, sabyenc is still in the addons repo as always.

**Comment by Safihre** [comment]
@jcfp but I remember on a fresh Ubuntu it just magically also fetched Sabyenc? Or did I just forget that I installed the additional repo?

**Comment by jcfp** [comment]
@Safihre recent debian and ubuntu versions also have sabyenc in their official repos, so it probably originated there. Can't guarantee that future sab releases (on the ppa) will still accept that -ever older- version of sabyenc though.
