### ISSUE TITLE
Improve: Servers

### ISSUE THREAD

**Issue by timrettop** [sabnzbd/sabnzbd.github.io#7]
## URL: /wiki/configuration/1.1/servers.html

Improvement:
Doesn't describe 'Backup' server tick box.

**Comment by shypike** [comment]
Backup servers no longer exist in SABnzbd. Replaced by priorities.
Only the example has a typo, which will be corrected.

**Comment by timrettop** [comment]
Thanks Shypike, I forgot that the ubuntu repository is behind the times, running 0.7.20.  Will update my software :)
