### ISSUE TITLE
Improve: Special settings

### ISSUE THREAD

**Issue by pumrum** [sabnzbd/sabnzbd.github.io#70]
## URL: /wiki/configuration/2.3/special.html

Improvement:
update **req_completion_rate** to clarify what allowed values are. Someone posted a good explanation here, but could be reworded to fit the wiki:
https://forums.sabnzbd.org/viewtopic.php?t=10808

> 100% means that of the available rar and par2 files only as many bytes
> are available as the required rar files comprise.
> Anything less than 100% is by definition not repairable.
> A perfect download (with the usual 10% par2 files) would have 110%.

**Comment by Safihre** [comment]
Updated the text 👍
