### ISSUE TITLE
Improve: Extensions for SABnzbd

### ISSUE THREAD

**Issue by geolaw** [sabnzbd/sabnzbd.github.io#71]
## URL: /wiki/extensions-for-sabnzbd.html

Improvement:
I believe this is a fork of the other HTPC-Manager - but s/XBMC/Plex/

https://github.com/Hellowlol/HTPC-Manager

**Comment by Safihre** [comment]
@Hellowlol, you are the new active maintainer? :)

**Comment by Hellowlol** [comment]
i wouldnt call me active. My fork is more updated then the other but i wouldn’t call it active. I’m hardly using it myself anymore.

**Comment by Safihre** [comment]
I added it as an alternative 👍
