### ISSUE TITLE
Improve: How to hide SABnzbd behind a webserver

### ISSUE THREAD

**Issue by trenb** [sabnzbd/sabnzbd.github.io#72]
## URL: /wiki/extra/howto-apache.html

Improvement:
nginx ssl.conf section recommends
```
ssl_protocols  SSLv2 SSLv3 TLSv1;
```
I would suggest to use the following instead as a minimum:
```
ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
```
or this if you're fancy (and want stronger crypto):
```
ssl_protocols  TLSv1.1 TLSv1.2;
```
This recommendation is due to the volume of attacks against both SSLv2 and SSLv3.

**Comment by sanderjo** [comment]
Oh, yes indeed. I will change that.

**Comment by trenb** [comment]
Wow, thanks! I wasn't expecting this to move so fast!

**Comment by sanderjo** [comment]
FWIW: Maybe you like this new option/feature in SABnzbd: 
https://github.com/sabnzbd/sabnzbd/commit/02b6f631568d4e769afe3bf0863e7cd552984ef1
