### ISSUE TITLE
Improve: Fedora and RHEL/CentOS/Scientific Linux RPM

### ISSUE THREAD

**Issue by fukie** [sabnzbd/sabnzbd.github.io#78]
## URL: /wiki/installation/install-fedora-centos-rhel.html

Improvement:

### Missing Command To Switch To Cloned Folder
```
git clone https://github.com/sabnzbd/sabnzbd
cd /opt/sabnzbd <--------- Add this
git checkout master

```

### Username Not Consistent With Product Name And Folder Name Incorrect

> Optionally create a SABnzbd user/group, optionally add user to shared group, and change ownership of the SABnzbd install to said user/group. Example:
```
useradd usenet
chown -R usenet:usenet /opt/usenet
```
To
```
useradd sabnzbd
chown -R sabnzbd:sabnzbd /opt/sabnzbd
```
### Username Consistency With Product Name In Service File
```
...
[Service]
Type=forking
User=usenet
Group=usenet
...
```

To 
```
...
[Service]
Type=forking
User=sabnzbd
Group=sabnzbd
...
```

### Use of sudo
Most of commands need sudo privileges but not indicated. While a few have 'sudo <command>'. 
Suggest to remove those 'sudo' from those commands and put a general comment on top to switch to a user with sudo privileges. OR, add 'sudo' to commands that lack them.

**Comment by Safihre** [comment]
Could you submit a PR? 
https://github.com/sabnzbd/sabnzbd.github.io/blob/master/wiki/installation/install-fedora-centos-rhel.html

**Comment by fukie** [comment]
Pull request #79 created. Should I close this issue?

**Comment by Safihre** [comment]
Thanks!
