### ISSUE TITLE
Improve: Python 3 - SABnzbd 3.0.0

### ISSUE THREAD

**Issue by carlwgeorge** [sabnzbd/sabnzbd.github.io#80]
## URL: /wiki/extra/python3.html

Improvement:
With the release of [CentOS 7.1908](https://lists.centos.org/pipermail/centos-announce/2019-September/023405.html), python3 is now in the main repos.  Adding IUS is no longer necessary.  Also, python3-pip pulls in python3 as a dependency, you don't have to specify them both.

```diff
-yum -y install https://centos7.iuscommunity.org/ius-release.rpm
-yum -y install git python36 python36-pip
+yum -y install git python3 python3-pip
```

**Comment by Safihre** [comment]
Feel free to open a PR and I'll merge it 👍
