### ISSUE TITLE
Improve: NZB Sources

### ISSUE THREAD

**Issue by hr1232** [sabnzbd/sabnzbd.github.io#86]
## URL: /wiki/introduction/nzb-sources.html

Improvement:

There's a free Spotweb open for registration without any API limits:
https://spotweb.me

**Comment by jcfp** [comment]
Is there any indication the admin of that site actually intends for it to be publicly available?

**Comment by hr1232** [comment]
Sorry for the late answer, my spam-filter ate GitHub's notice.

As I am the admin of that site, I can give you a definite Yes.
