### ISSUE TITLE
Improve: SABYenc

### ISSUE THREAD

**Issue by badabing2** [sabnzbd/sabnzbd.github.io#89]
## URL: /wiki/installation/sabyenc.html

Improvement:
Install issue Ubuntu 20.04 (latest 5/29/2020)
Everything worked except the grand finale.

sudo apt-get install sabnzbdplus python-sabyenc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-sabyenc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-sabyenc' has no installation candidate

**Comment by sanderjo** [comment]
Ubuntu 20.04 has sabnzbdplus version 3 in the standard repo, including dependencies, so if you install that ... 

And, hint: `python3-sabyenc`

**Comment by jcfp** [comment]
@badabing2 does have a point, things should just work for folks actually following instructions.

Better to just omit sabyenc from the command line. In most cases (including all sab v3 installs), it would still be installed as a dependency anyway.

Fixed in 9c0a5946372667895a206aaccd5f12ed896adf00.

**Comment by badabing2** [comment]
The update works like a charm. Just a note to say you guys rock, much appreciated!
saludos,~alan 

    On Saturday, May 30, 2020, 12:06:05 AM PDT, jcfp <notifications@github.com> wrote:  
 
 


@badabing2 does have a point, things should just work for folks actually following instructions.

Better to just omit sabyenc from the command line. In most cases (including all sab v3 installs), it would still be installed as a dependency anyway.

Fixed in 9c0a594.
